package Modulos;

import Clases.Repositorio;
import Entidades.Configuracion;
import Entidades.SignerPDF;
import Entidades.Firmador;
import Entidades.Firmante;
import Formularios.frmConfigurador;
import Global.CConstantes;
import static Modulos.frmFirmador.properties;
import java.awt.Color;
import java.awt.Desktop;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadPoolExecutor;
import javax.swing.JButton;
import javax.swing.JLabel;
import org.apache.commons.io.FileUtils;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;


public class frmOtrosDatos extends javax.swing.JDialog
{
    Thread hilofirma;
    Firmante firmante;

    public frmOtrosDatos(java.awt.Dialog parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        jLabel2.setVisible(false);
        txtlocalidad.setVisible(false);
        btnVerDocumentoFirmado.setEnabled(false);
        cambiarColor(btnVerDocumentoFirmado, java.awt.Color.white, new Color(97, 120, 134));
        txtFirmante.setText(frmFirmador.configuracion.getFirmante().getCertificado().getCn());
        txtEmpresa.setText(frmFirmador.configuracion.getFirmante().getCertificado().getEmpresa());
        txtCargo.setText(frmFirmador.configuracion.getFirmante().getCertificado().getCargo());
        txtmotivo.setText(frmFirmador.configuracion.getVg_motivo());
        //txtmotivo.setText("SSigner Configuración v 2.5.1.1");
        
        this.firmante = frmFirmador.repositorios.getFirmanteElegido();
        
        if (txtmotivo.getText().length() > 0)
        {
            txtmotivo.setSelectionStart(0);
            txtmotivo.setSelectionEnd(txtmotivo.getText().length());
        }

        //txtlocalidad.setText(frmFirmador.configuracion.getVg_localidad());    
        txtlocalidad.setText("SSigner Configuración v 2.5.1.1");    

        if (txtlocalidad.getText().length() > 0) {
            txtlocalidad.setEnabled(false);  // Deshabilitar el campo
            txtlocalidad.setBackground(new Color(105, 105, 105));  // Cambiar el fondo a gris
            txtlocalidad.setForeground(new Color(25, 25, 112) );
        } else {
            txtlocalidad.setEnabled(true);  // Habilitar el campo si no está seteado
            txtlocalidad.setBackground(Color.WHITE);  // Fondo blanco
        }
    }

    public frmOtrosDatos(java.awt.Dialog parent, boolean modal, Firmador firmar, Firmante firmante)
    {
        super(parent, modal);
        initComponents();
        btnVerDocumentoFirmado.setEnabled(false);
        cambiarColor(btnVerDocumentoFirmado, java.awt.Color.white, new Color(97, 120, 134));
        this.firmante = firmante;
        txtFirmante.setText(firmar.getC_nombre());
        txtEmpresa.setText(firmar.getC_empresa());
        txtCargo.setText(firmar.getC_titulo());
        txtmotivo.setText(frmFirmador.configuracion.getVg_motivo());
        
        if (txtmotivo.getText().length() > 0)
        {
            txtmotivo.setSelectionStart(0);
            txtmotivo.setSelectionEnd(txtmotivo.getText().length());
        }

        txtlocalidad.setText(frmFirmador.configuracion.getVg_localidad());
    }

    void grabarPropiedad(String key, String valor)
    {
        try (FileOutputStream fos = new FileOutputStream(new File(Global.CConstantes.RUTAPROPIEDADES)))
        {
            properties.setProperty(key, valor);
            properties.store(fos, "SSigner");
            fos.close();
        }
        catch (IOException ex)
        {
            txtRespuesta.setText(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pnlOtrosDatos = new javax.swing.JPanel();
        pnlBarra5 = new javax.swing.JPanel();
        lblCerrar5 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnLogo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtmotivo = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtFirmante = new javax.swing.JTextField();
        txtEmpresa = new javax.swing.JTextField();
        txtlocalidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnFirmar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRespuesta = new javax.swing.JTextArea();
        btnVerDocumentoFirmado = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        pnlOtrosDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlOtrosDatos.setPreferredSize(new java.awt.Dimension(431, 296));

        pnlBarra5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBarra5.setMinimumSize(new java.awt.Dimension(480, 34));

        lblCerrar5.setBackground(new java.awt.Color(255, 102, 102));
        lblCerrar5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblCerrar5.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar5.setText("x");
        lblCerrar5.setToolTipText("Cerrar");
        lblCerrar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar5.setMaximumSize(new java.awt.Dimension(41, 30));
        lblCerrar5.setMinimumSize(new java.awt.Dimension(41, 30));
        lblCerrar5.setOpaque(true);
        lblCerrar5.setPreferredSize(new java.awt.Dimension(41, 30));
        lblCerrar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrar5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrar5MouseExited(evt);
            }
        });

        lblTitulo.setBackground(new java.awt.Color(0, 51, 102));
        lblTitulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("OTROS DATOS");

        btnLogo.setBackground(new java.awt.Color(255, 255, 255));
        btnLogo.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        btnLogo.setForeground(new java.awt.Color(255, 255, 255));
        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo Ssigner-01.png"))); // NOI18N
        btnLogo.setToolTipText("Cargar documentos para visualzar.");
        btnLogo.setAutoscrolls(true);
        btnLogo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnLogo.setBorderPainted(false);
        btnLogo.setContentAreaFilled(false);
        btnLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogo.setFocusPainted(false);
        btnLogo.setMaximumSize(new java.awt.Dimension(55, 26));
        btnLogo.setMinimumSize(new java.awt.Dimension(55, 26));
        btnLogo.setPreferredSize(new java.awt.Dimension(55, 26));
        btnLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoMouseExited(evt);
            }
        });
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBarra5Layout = new javax.swing.GroupLayout(pnlBarra5);
        pnlBarra5.setLayout(pnlBarra5Layout);
        pnlBarra5Layout.setHorizontalGroup(
            pnlBarra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarra5Layout.createSequentialGroup()
                .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lblTitulo)
                .addGap(196, 196, 196)
                .addComponent(lblCerrar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBarra5Layout.setVerticalGroup(
            pnlBarra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblCerrar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarra5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(btnLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        txtmotivo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtmotivo.setPreferredSize(new java.awt.Dimension(366, 27));
        txtmotivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmotivoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmotivoFocusLost(evt);
            }
        });

        txtCargo.setBackground(new java.awt.Color(204, 204, 204));
        txtCargo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtCargo.setForeground(new java.awt.Color(211, 111, 66));
        txtCargo.setText("-");
        txtCargo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCargo.setEnabled(false);
        txtCargo.setPreferredSize(new java.awt.Dimension(366, 27));

        txtFirmante.setBackground(new java.awt.Color(204, 204, 204));
        txtFirmante.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtFirmante.setForeground(new java.awt.Color(211, 111, 66));
        txtFirmante.setText("-");
        txtFirmante.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFirmante.setEnabled(false);
        txtFirmante.setPreferredSize(new java.awt.Dimension(366, 27));

        txtEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        txtEmpresa.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtEmpresa.setForeground(new java.awt.Color(211, 111, 66));
        txtEmpresa.setText("-");
        txtEmpresa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEmpresa.setEnabled(false);
        txtEmpresa.setPreferredSize(new java.awt.Dimension(366, 27));

        txtlocalidad.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtlocalidad.setPreferredSize(new java.awt.Dimension(366, 27));
        txtlocalidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlocalidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlocalidadFocusLost(evt);
            }
        });
        txtlocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlocalidadActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("FIRMANTE  ");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel5.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("EMPRESA  ");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(0, 51, 102));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("CARGO  ");
        jLabel4.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("MOTIVO  ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("LOCALIDAD  ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtmotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtlocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtFirmante, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFirmante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtlocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jLayeredPane1.setBackground(new java.awt.Color(240, 240, 240));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(480, 52));
        jLayeredPane1.setOpaque(true);

        btnFirmar.setBackground(new java.awt.Color(211, 111, 66));
        btnFirmar.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnFirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnFirmar.setText("FIRMAR");
        btnFirmar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(211, 111, 66), new java.awt.Color(211, 111, 66)));
        btnFirmar.setContentAreaFilled(false);
        btnFirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFirmar.setDefaultCapable(false);
        btnFirmar.setFocusPainted(false);
        btnFirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFirmar.setOpaque(true);
        btnFirmar.setPreferredSize(new java.awt.Dimension(87, 30));
        btnFirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFirmarMouseExited(evt);
            }
        });
        btnFirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirmarActionPerformed(evt);
            }
        });

        txtRespuesta.setEditable(false);
        txtRespuesta.setColumns(20);
        txtRespuesta.setLineWrap(true);
        txtRespuesta.setRows(5);
        jScrollPane2.setViewportView(txtRespuesta);

        btnVerDocumentoFirmado.setBackground(new java.awt.Color(211, 111, 66));
        btnVerDocumentoFirmado.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnVerDocumentoFirmado.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDocumentoFirmado.setText("VER");
        btnVerDocumentoFirmado.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(211, 111, 66), new java.awt.Color(211, 111, 66)));
        btnVerDocumentoFirmado.setContentAreaFilled(false);
        btnVerDocumentoFirmado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerDocumentoFirmado.setDefaultCapable(false);
        btnVerDocumentoFirmado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerDocumentoFirmado.setOpaque(true);
        btnVerDocumentoFirmado.setPreferredSize(new java.awt.Dimension(87, 30));
        btnVerDocumentoFirmado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerDocumentoFirmadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerDocumentoFirmadoMouseExited(evt);
            }
        });
        btnVerDocumentoFirmado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDocumentoFirmadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerDocumentoFirmado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnFirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnVerDocumentoFirmado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jLayeredPane1.setLayer(btnFirmar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVerDocumentoFirmado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlOtrosDatosLayout = new javax.swing.GroupLayout(pnlOtrosDatos);
        pnlOtrosDatos.setLayout(pnlOtrosDatosLayout);
        pnlOtrosDatosLayout.setHorizontalGroup(
            pnlOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOtrosDatosLayout.createSequentialGroup()
                .addGroup(pnlOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlBarra5, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOtrosDatosLayout.setVerticalGroup(
            pnlOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOtrosDatosLayout.createSequentialGroup()
                .addComponent(pnlBarra5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlOtrosDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOtrosDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void cerrarVentana()
    {
        frmCertificados.cerrarventana = 1;
        setVisible(false);
        dispose();
    }

    protected void cambiarColor(Object obj, Color colorfondo, Color colorletra)
    {
        if (obj instanceof javax.swing.JLabel)
        {
            ((javax.swing.JLabel) obj).setBackground(colorfondo);
            ((javax.swing.JLabel) obj).setForeground(colorletra);
            ((javax.swing.JLabel) obj).setOpaque(true);
        }
        else if (obj instanceof JButton)
        {
            ((javax.swing.JButton) obj).setBackground(colorfondo);
            ((javax.swing.JButton) obj).setForeground(colorletra);
            ((javax.swing.JButton) obj).setOpaque(true);
            ((javax.swing.JButton) obj).setBorder(javax.swing.BorderFactory.createLineBorder(colorletra));
        }
    }

    void focodentro(javax.swing.JTextField cajatexto)
    {
        cajatexto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(67, 73, 111), 2, true));
    }

    void focofuera(javax.swing.JTextField cajatexto)
    {
        cajatexto.setBorder(txtFirmante.getBorder());
    }
    
    private void lblCerrar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar5MouseClicked
        cerrarVentana();
    }//GEN-LAST:event_lblCerrar5MouseClicked

    private void lblCerrar5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar5MouseEntered
        cambiarColor((javax.swing.JLabel) evt.getSource(), java.awt.Color.red, java.awt.Color.white);
    }//GEN-LAST:event_lblCerrar5MouseEntered

    private void lblCerrar5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar5MouseExited
        cambiarColor((javax.swing.JLabel) evt.getSource(), new java.awt.Color(255, 102, 102), java.awt.Color.WHITE);

    }//GEN-LAST:event_lblCerrar5MouseExited
    
    public static int termino = 0;

    public synchronized static void terminarProceso(int i)
    {
        if (frmFirmador.dgvDocumentos.getRowCount() - 1 == i)
        {
            btnFirmar.setText("FIRMANDO");
            termino = 1;
        }
    }
    
    private void btnFirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirmarActionPerformed
        try
        {
            firmar();
        }
        catch (Exception ex)
        {
            CConstantes.dialogo("Exception " + ex.getMessage());
        }
    }//GEN-LAST:event_btnFirmarActionPerformed

    void firmar() throws Exception
    {
        new Thread(new Runnable()
        {
            @Override
            public void run()
            {
                frmConfigurador.validarCertificado1(firmante.getCertificado());    
                btnFirmar.setEnabled(false);
                btnFirmar.setText("FIRMANDO");
                cambiarColor(btnFirmar, java.awt.Color.white, new Color(97, 120, 134));
                    
                frmFirmador.configuracion.setVg_motivo(txtmotivo.getText());
                frmFirmador.configuracion.setVg_localidad(txtlocalidad.getText());
                
                Firmador firmador = new Firmador(frmFirmador.configuracion.getDocumentoUltimo());
                frmFirmador.configuracion.setVg_motivo(txtmotivo.getText());
                frmFirmador.configuracion.setVg_localidad(txtlocalidad.getText());
                firmador.setC_locacion(frmFirmador.configuracion.getVg_localidad());
                firmador.setC_motivo(frmFirmador.configuracion.getVg_motivo());
                firmador.setC_otros("");
                //***FIN FIRMA VISIBLE***////
                firmador.setTipoResumen(frmFirmador.configuracion.getVg_algoritmo());
                grabarPropiedad(Global.CConstantes.CERTMOTIVO, frmFirmador.configuracion.getVg_motivo());
                grabarPropiedad(Global.CConstantes.CERTLOCACION, frmFirmador.configuracion.getVg_localidad());

                firmador.setListarutas(frmFirmador.configuracion.getRutasdocumentos());
                firmador.setContador(new JLabel());
                firmador.setBaseancho((int) frmFirmador.configuracion.getVg_firma_visible_ancho_base());
                firmador.setBasealto((int) frmFirmador.configuracion.getVg_firma_visible_alto_base());
                firmador.setNro_pagina("" + frmFirmador.configuracion.getVg_firma_visible_pagina());
                firmador.setFirma_visible(frmFirmador.configuracion.isVg_firma_visible());
                firmador.setRuta_imagen(frmFirmador.configuracion.getVg_firma_visible_ruta_imagen());

                if(frmFirmador.configuracion.getEtiqueta_firma() == null || "".equals(frmFirmador.configuracion.getEtiqueta_firma()))
                {
                    firmador.setX((int) frmFirmador.configuracion.getVg_firma_visible_x());
                    firmador.setY((int) frmFirmador.configuracion.getVg_firma_visible_y());
                    firmador.setAncho((int) frmFirmador.configuracion.getVg_firma_visible_x1());
                    firmador.setAlto((int) frmFirmador.configuracion.getVg_firma_visible_y1());
                }
                else
                {
                    /*byte[] bytesArray = readBytesFromFile(frmFirmador.configuracion.getDocumentoUltimo());
                    float[] coordenadas;
                    coordenadas = getCoordenadas(bytesArray, frmFirmador.configuracion.getEtiqueta_firma());
                    firmador.setX((int)coordenadas[0]);
                    firmador.setY((int)coordenadas[1]);*/
                    firmador.setX((int) frmFirmador.configuracion.getVg_firma_visible_x());
                    firmador.setY((int) frmFirmador.configuracion.getVg_firma_visible_y());
                    firmador.setAncho((int)frmFirmador.configuracion.getVg_firma_visible_x1());
                    firmador.setAlto((int)frmFirmador.configuracion.getVg_firma_visible_y1());
                }

                int cboEstilo = frmFirmador.configuracion.getVg_firma_visible_estilo_firma();
                switch (cboEstilo)
                {
                    case 0:
                        firmador.setFirma_visible_solo_imagen(true);
                        break;
                    case 1:
                        firmador.setFirma_visible_solo_texto(true);
                        break;
                    case 2:
                        firmador.setFirma_visible_imagen_texto(true);
                        break;
                        
                    case 3:
                        firmador.setFirma_visible_imagen_texto(true);
                        firmador.setFirma_visible_imagen_texto_lado(true);
                        break;
                }

                firmador.setUrl_tsa(frmFirmador.configuracion.getVg_tsa_url());
                firmador.setUsuario_tsa(frmFirmador.configuracion.getVg_tsa_usuario());
                firmador.setPassword_tsa(frmFirmador.configuracion.getVg_tsa_clave());
                firmador.setC_nombre(firmante.getCertificado().getCn());//lblValorEmisor.getText());
                firmador.setC_area(firmante.getCertificado().getOu());
                firmador.setC_titulo(firmante.getCertificado().getCargo());//lblTitle.getText());
                firmador.setC_empresa(firmante.getCertificado().getEmpresa());//lblO.getText());
                firmador.setFirma_visible_todas_paginas(frmFirmador.configuracion.isVg_firma_visible_firmar_todas_paginas());
                firmador.setVarias_firmas(frmFirmador.configuracion.isVg_cerrar_documento());
                firmador.setCarpeta_salida(frmFirmador.configuracion.getVg_carpeta_salida());
                firmador.setConNumeroCal(frmFirmador.configuracion.getConNumeroCal());
                firmador.setConCampoArea(frmFirmador.configuracion.getConCarmpoArea());
                firmador.setTipoResumen(frmFirmador.configuracion.getVg_algoritmo());
                firmador.setTextoFirmador(frmFirmador.configuracion.getVg_texto_firmante());
                firmador.setConCampoEmpresa(frmFirmador.configuracion.getConCampoEmpresa());
                frmFirmador.configuracion.setFirmante(firmante);
                frmFirmador.repositorios.setFirmanteElegido(firmante);

                if (frmFirmador.configuracion.getModalidad().equals(Configuracion.getServer()))
                {
                    //Server
                    ThreadPoolExecutor executor = (ThreadPoolExecutor) Executors.newFixedThreadPool(2);
                    //frmFirmador.configuracion.setVg_firma_visible(false);
                    CConstantes constantes = new CConstantes();
                    
                    for (int i = 0; i < frmFirmador.configuracion.getRutasdocumentos().size(); i++)
                    {
                        try
                        {
                            String rep = frmFirmador.repositorios.getProveedor().getName();
            
                            if(frmFirmador.repositorios.getNombreAlmacen().equals(Repositorio.ARCHIVO))
                                    rep = "BC";

                            Thread hiloFirmador = new SignerPDF(
                                constantes.getErrores(),
                                new File(frmFirmador.configuracion.getRutasdocumentos().get(i)).getAbsolutePath(),
                                new File(frmFirmador.configuracion.getRutasdocumentos().get(i)).getParentFile().getAbsolutePath(), (frmFirmador.configuracion.getVg_carpeta_salida().equals("") ? frmFirmador.configuracion.getVg_carpeta_salida() : frmFirmador.configuracion.getVg_carpeta_salida().trim()),
                                firmante.getCertificado().getAlias(),
                                firmante.getCertificado().getLlavePrivada(),
                                firmante.getCertificado().getCertificadosConfianza(),
                                firmante.getCertificado().getCertificadoX509(),
                                true,
                                frmFirmador.repositorios.getFirmanteElegido().getCertificado().getCn(),
                                frmFirmador.configuracion.getVg_carpeta_salida_crl_tsl(), i, rep);

                            executor.execute(hiloFirmador);
                        }
                        catch (Exception e) {  }                        
                    }
                    
                    frmCertificados.cerrarventana = 1;
                    setVisible(false);
                }
                else
                {
                    //User
                    try
                    {
                        firmador.setListarutas(frmFirmador.configuracion.getRutasdocumentos());
                        String respuetsa = firmador.firmar(frmFirmador.repositorios, txtRespuesta);

                        if (respuetsa.equals(CConstantes.X_ERROR))
                        {
                            btnVerDocumentoFirmado.setEnabled(false);
                            cambiarColor(btnVerDocumentoFirmado, java.awt.Color.white, new Color(97, 120, 134));
                        }
                        else
                        {
                            btnVerDocumentoFirmado.setEnabled(true);
                            cambiarColor(btnVerDocumentoFirmado, new Color(211, 111, 66), java.awt.Color.white);
                        }
                    }
                    catch (Exception ex)
                    {
                        txtRespuesta.setText("Excepción al firmar: " + ex.getMessage());
                    }
                }
                
                btnFirmar.setText("FIRMAR");
                btnFirmar.setEnabled(true);
                cambiarColor(btnFirmar, new Color(211, 111, 66), java.awt.Color.white);
            }
        }).start();
    }
    
    private float[] getCoordenadas(byte[] archivoPDF, String etiqueta)
    {
        float[] coordenadas = new float[] {0, 0, 0};
        
        try (InputStream fis = new ByteArrayInputStream(archivoPDF); PDDocument document1 = PDDocument.load(fis))
        {
            PDFTextStripper pdfStripper = new GetCharLocalizationAndSize();
            boolean breakit = false;
            
            etiqueta = "[" + etiqueta + "]";
            
            ((GetCharLocalizationAndSize)pdfStripper).setTag(etiqueta);
            
            for (int k = 1; k <= document1.getNumberOfPages(); k++)
            {
                pdfStripper.setStartPage(k);
                pdfStripper.setEndPage(k);
                
                String text01 = pdfStripper.getText(document1);
                String[] text = text01.split("\\r?\\n");
                
                for (int i = 0; i < text.length; i++)
                {
                    if(text[i].toUpperCase().contains(etiqueta.toUpperCase()))
                    {
                        String[] temp = text[i].split("\\Q][\\E"); // a veces se dan las coordenadas de más de un texto

                        for (int j = 0; j < temp.length; j++)
                            if(temp[j].toUpperCase().contains(etiqueta.toUpperCase()))
                            {
                                String[] temp2 = temp[j].split(",");
                                coordenadas = new float[] { 
                                    Float.valueOf(temp2[0].replace("[", "").replace("]", "")) - 20, 
                                    document1.getPage(k - 1).getBBox().getHeight() - Float.valueOf(temp2[1].replace("[", "").replace("]", "")) - 6, 
                                    k };
                                
                                breakit = true;
                                break;
                            }
                    }
                    
                    if (breakit)
                        break;
                }

                if (breakit)
                    break;
            }
        }
        catch(Exception e) {  }
        
        return coordenadas;
    }
  
    private static byte[] readBytesFromFile(String filePath)
    {
        byte[] bytesArray = null;

        try
        {
            File file = new File(filePath);
            bytesArray = FileUtils.readFileToByteArray(file);
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }

        return bytesArray;
    }

    private void btnFirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirmarMouseEntered
        if (btnFirmar.isEnabled()) {
            cambiarColor((javax.swing.JButton) evt.getSource(), java.awt.Color.white, new Color(211, 111, 66));
        }
    }//GEN-LAST:event_btnFirmarMouseEntered

    private void btnFirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirmarMouseExited
        if (btnFirmar.isEnabled()) {
            cambiarColor((javax.swing.JButton) evt.getSource(), new Color(211, 111, 66), java.awt.Color.white);
        }
    }//GEN-LAST:event_btnFirmarMouseExited

    private void txtmotivoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmotivoFocusGained
        focodentro((javax.swing.JTextField) evt.getSource());
    }//GEN-LAST:event_txtmotivoFocusGained

    private void txtmotivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmotivoFocusLost
        focofuera((javax.swing.JTextField) evt.getSource());
    }//GEN-LAST:event_txtmotivoFocusLost

    private void txtlocalidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlocalidadFocusGained
        focodentro((javax.swing.JTextField) evt.getSource());
    }//GEN-LAST:event_txtlocalidadFocusGained

    private void txtlocalidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlocalidadFocusLost
        focofuera((javax.swing.JTextField) evt.getSource());
    }//GEN-LAST:event_txtlocalidadFocusLost

    private void btnLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoMouseEntered

    private void btnLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoMouseExited

    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoActionPerformed

    private void txtlocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocalidadActionPerformed

    private void btnVerDocumentoFirmadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerDocumentoFirmadoMouseEntered
        if (btnVerDocumentoFirmado.isEnabled())
            cambiarColor((javax.swing.JButton) evt.getSource(), java.awt.Color.white, new Color(211, 111, 66));
    }//GEN-LAST:event_btnVerDocumentoFirmadoMouseEntered

    private void btnVerDocumentoFirmadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerDocumentoFirmadoMouseExited
        if (btnVerDocumentoFirmado.isEnabled())
            cambiarColor((javax.swing.JButton) evt.getSource(), new Color(211, 111, 66), java.awt.Color.white);
    }//GEN-LAST:event_btnVerDocumentoFirmadoMouseExited

    private void btnVerDocumentoFirmadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDocumentoFirmadoActionPerformed
        if (Desktop.isDesktopSupported())
        {
            try
            {
                Desktop.getDesktop().open(new File(frmFirmador.configuracion.getVg_carpeta_salida()));
                // Desktop.getDesktop().open(new File(firmar.getDoc_carpeta_salida_ruta()));
            } 
            catch (IOException ex)
            {
                txtRespuesta.setText("error: " + ex.getMessage());
            }
        } 
        else
            txtRespuesta.setText("El sistema operativo no soporta esta caracteristica de la aplicaion, Los archivos los puede encontra en la siguiente ruta:" + frmFirmador.configuracion.getVg_carpeta_salida());
    }//GEN-LAST:event_btnVerDocumentoFirmadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnFirmar;
    public javax.swing.JButton btnLogo;
    public static javax.swing.JButton btnVerDocumentoFirmado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCerrar5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBarra5;
    private javax.swing.JPanel pnlOtrosDatos;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtFirmante;
    private javax.swing.JTextArea txtRespuesta;
    private javax.swing.JTextField txtlocalidad;
    private javax.swing.JTextField txtmotivo;
    // End of variables declaration//GEN-END:variables
}
