/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author usuario
 */
public class frmAcercaDe extends javax.swing.JDialog {

    /**
     * Creates new form frmAcercaDe
     */
    public frmAcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
   private void cerrarVentana(){
            setVisible(false);
            dispose();
    }
    protected void cambiarColor(Object obj){
        cambiarColor(obj,Color.lightGray,Color.white);
    }
    protected void cambiarColor(Object obj,Color colorfondo,Color colorletra){
        if(obj instanceof javax.swing.JLabel){
            ((javax.swing.JLabel) obj).setBackground(colorfondo);
            ((javax.swing.JLabel) obj).setForeground(colorletra);
            ((javax.swing.JLabel) obj).setOpaque(true);
        }
        else if(obj instanceof JButton){
            ((JButton) obj).setBackground(colorfondo);
            ((javax.swing.JLabel) obj).setForeground(colorletra);
            ((javax.swing.JLabel) obj).setOpaque(true);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnCargar1 = new javax.swing.JButton();
        pnlBarra3 = new javax.swing.JPanel();
        lblCerrar3 = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        ctrl_lbl_ver_manual = new javax.swing.JLabel();
        ctrl_lbl_ir_url_salmon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ctrl_txt_cuerpo_descripcion = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCargar1.setBackground(new java.awt.Color(211, 111, 66));
        btnCargar1.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        btnCargar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar1.setToolTipText("Cargar documentos para visualzar.");
        btnCargar1.setAutoscrolls(true);
        btnCargar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnCargar1.setBorderPainted(false);
        btnCargar1.setContentAreaFilled(false);
        btnCargar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargar1.setFocusPainted(false);
        btnCargar1.setPreferredSize(new java.awt.Dimension(55, 26));
        btnCargar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCargar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCargar1MouseExited(evt);
            }
        });
        btnCargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargar1ActionPerformed(evt);
            }
        });

        pnlBarra3.setBackground(new java.awt.Color(241, 241, 241));
        pnlBarra3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        lblCerrar3.setBackground(new java.awt.Color(255, 153, 153));
        lblCerrar3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblCerrar3.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar3.setText("x");
        lblCerrar3.setToolTipText("Cerrar");
        lblCerrar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar3.setOpaque(true);
        lblCerrar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrar3MouseExited(evt);
            }
        });

        lbltitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("Acerca de");

        javax.swing.GroupLayout pnlBarra3Layout = new javax.swing.GroupLayout(pnlBarra3);
        pnlBarra3.setLayout(pnlBarra3Layout);
        pnlBarra3Layout.setHorizontalGroup(
            pnlBarra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarra3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCerrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBarra3Layout.setVerticalGroup(
            pnlBarra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblCerrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ctrl_lbl_ver_manual.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ctrl_lbl_ver_manual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ctrl_lbl_ver_manual.setText("ver manual de usuario");
        ctrl_lbl_ver_manual.setToolTipText("clic para ver manual de usuario");
        ctrl_lbl_ver_manual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ctrl_lbl_ir_url_salmon.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ctrl_lbl_ir_url_salmon.setForeground(new java.awt.Color(0, 51, 204));
        ctrl_lbl_ir_url_salmon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ctrl_lbl_ir_url_salmon.setText("www.saeta.pe/ssigner");
        ctrl_lbl_ir_url_salmon.setToolTipText("www.saeta.pe/ssigner");
        ctrl_lbl_ir_url_salmon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ctrl_lbl_ir_url_salmon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctrl_lbl_ir_url_salmonMouseClicked(evt);
            }
        });

        jScrollPane1.setBorder(null);

        ctrl_txt_cuerpo_descripcion.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        ctrl_txt_cuerpo_descripcion.setText("SSigner Configurador es una flexible e intuitiva herramienta para el usuario, posee propiedades fáciles de configurar y rápido alcance en el ambiente que se halle, Dispone de procesos de Firma Digital, Sellado de Tiempo.");
        ctrl_txt_cuerpo_descripcion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ctrl_txt_cuerpo_descripcion.setEnabled(false);
        jScrollPane1.setViewportView(ctrl_txt_cuerpo_descripcion);

        jButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBarra3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctrl_lbl_ver_manual, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctrl_lbl_ir_url_salmon, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCargar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBarra3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ctrl_lbl_ir_url_salmon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrl_lbl_ver_manual)
                .addGap(24, 24, 24))
        );

        ctrl_lbl_ir_url_salmon.getAccessibleContext().setAccessibleDescription("www.saeta.pe/ssigner");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar1MouseEntered

    private void btnCargar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar1MouseExited

    private void btnCargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar1ActionPerformed

    private void lblCerrar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar3MouseClicked
        cerrarVentana();
    }//GEN-LAST:event_lblCerrar3MouseClicked

    private void lblCerrar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar3MouseEntered
        cambiarColor((javax.swing.JLabel)evt.getSource(),Color.red,Color.white);
    }//GEN-LAST:event_lblCerrar3MouseEntered

    private void lblCerrar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar3MouseExited
        cambiarColor((javax.swing.JLabel)evt.getSource(),new Color(255,153,153),Color.white);
    }//GEN-LAST:event_lblCerrar3MouseExited

    private void ctrl_lbl_ir_url_salmonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctrl_lbl_ir_url_salmonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ctrl_lbl_ir_url_salmonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCargar1;
    private javax.swing.JLabel ctrl_lbl_ir_url_salmon;
    private javax.swing.JLabel ctrl_lbl_ver_manual;
    private javax.swing.JTextPane ctrl_txt_cuerpo_descripcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCerrar3;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel pnlBarra3;
    // End of variables declaration//GEN-END:variables
}
