/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Firmante;

/**
 *
 * @author usuario
 */
public class frmCertificadoPropiedades extends javax.swing.JDialog {

    /**
     * Creates new form frmCertificadoPropiedades
     */
    public frmCertificadoPropiedades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    public frmCertificadoPropiedades(java.awt.Frame parent, boolean modal, Firmante.Certificado p_certificado) {
        super(parent, modal);

        initComponents();
        lbl_crt_usos.setText(p_certificado.getUso());
        lbl_crt_emi_por.setText(p_certificado.getDn());
        lbl_crt_emi_par.setText(p_certificado.getCn());
        lbl_crt_alia.setText(p_certificado.getAlias());
        lbl_crt_crg.setText(p_certificado.getCargo());
        lbl_crt_emp.setText(p_certificado.getEmpresa());
        lbl_crt_ser_num.setText(p_certificado.getSerie());
        lbl_crt_uni_org.setText(p_certificado.getEmpresa());
        lbl_crt_val_des.setText(p_certificado.getFechaInicial());
        lbl_crt_val_has.setText(p_certificado.getFechafinal());
        lbl_crt_uso.setText(p_certificado.getUso());
        ayuda_mensaje_setear(lbl_crt_usos);
        ayuda_mensaje_setear(lbl_crt_emi_por);
        ayuda_mensaje_setear(lbl_crt_emi_par);
        ayuda_mensaje_setear(lbl_crt_alia);
        ayuda_mensaje_setear(lbl_crt_crg);
        ayuda_mensaje_setear(lbl_crt_emp);
        ayuda_mensaje_setear(lbl_crt_ser_num);
        ayuda_mensaje_setear(lbl_crt_uni_org);
        ayuda_mensaje_setear(lbl_crt_val_des);
        ayuda_mensaje_setear(lbl_crt_val_has);
        ayuda_mensaje_setear(lbl_crt_uso);
        setLocationRelativeTo(parent);

    }

    public frmCertificadoPropiedades(java.awt.Dialog parent, boolean modal, Firmante.Certificado p_certificado) {
        super(parent, modal);

        initComponents();
        lbl_crt_usos.setText(p_certificado.getUso());
        lbl_crt_emi_por.setText(p_certificado.getDn());
        lbl_crt_emi_par.setText(p_certificado.getCn());
        lbl_crt_alia.setText(p_certificado.getAlias());
        lbl_crt_crg.setText(p_certificado.getCargo());
        lbl_crt_emp.setText(p_certificado.getEmpresa());
        lbl_crt_ser_num.setText(p_certificado.getSerie());
        lbl_crt_uni_org.setText(p_certificado.getEmpresa());
        lbl_crt_val_des.setText(p_certificado.getFechaInicial());
        lbl_crt_val_has.setText(p_certificado.getFechafinal());
        lbl_crt_uso.setText(p_certificado.getUso());
        ayuda_mensaje_setear(lbl_crt_usos);
        ayuda_mensaje_setear(lbl_crt_emi_por);
        ayuda_mensaje_setear(lbl_crt_emi_par);
        ayuda_mensaje_setear(lbl_crt_alia);
        ayuda_mensaje_setear(lbl_crt_crg);
        ayuda_mensaje_setear(lbl_crt_emp);
        ayuda_mensaje_setear(lbl_crt_ser_num);
        ayuda_mensaje_setear(lbl_crt_uni_org);
        ayuda_mensaje_setear(lbl_crt_val_des);
        ayuda_mensaje_setear(lbl_crt_val_has);
        ayuda_mensaje_setear(lbl_crt_uso);
        setLocationRelativeTo(parent);

    }

    private void ayuda_mensaje_setear(Object p_obj) {
        if (p_obj instanceof javax.swing.JLabel) {
            ((javax.swing.JLabel) p_obj).setToolTipText(((javax.swing.JLabel) p_obj).getText().trim().equals("") ? null : ((javax.swing.JLabel) p_obj).getText());
        } else if (p_obj instanceof javax.swing.JButton) {
            ((javax.swing.JButton) p_obj).setToolTipText(((javax.swing.JButton) p_obj).getText().trim().equals("") ? null : ((javax.swing.JButton) p_obj).getText());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnl_principal_cabecera = new javax.swing.JPanel();
        txt_vtn_tit = new javax.swing.JLabel();
        txt_vtn_btn_cer = new javax.swing.JLabel();
        txt_vtn_ico = new javax.swing.JButton();
        pnlCertificadoDetalles = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_msj_ico = new javax.swing.JLabel();
        txt_vtn_tit1 = new javax.swing.JLabel();
        txt_vtn_tit2 = new javax.swing.JLabel();
        txt_vtn_tit3 = new javax.swing.JLabel();
        lbl_crt_usos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_crt_emi_por = new javax.swing.JLabel();
        lbl_crt_emi_par = new javax.swing.JLabel();
        lbl_crt_alia = new javax.swing.JLabel();
        lbl_crt_crg = new javax.swing.JLabel();
        lbl_crt_emp = new javax.swing.JLabel();
        lbl_crt_ser_num = new javax.swing.JLabel();
        lbl_crt_uni_org = new javax.swing.JLabel();
        lbl_crt_val_des = new javax.swing.JLabel();
        lbl_crt_val_has = new javax.swing.JLabel();
        lbl_crt_uso = new javax.swing.JLabel();
        lbl_crt_emi_ver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlPrincipal.setBackground(new java.awt.Color(241, 241, 241));
        pnlPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnl_principal_cabecera.setOpaque(false);

        txt_vtn_tit.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        txt_vtn_tit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_vtn_tit.setText("CERTIFICADO");
        txt_vtn_tit.setBorder(null);

        txt_vtn_btn_cer.setBackground(new java.awt.Color(255, 153, 153));
        txt_vtn_btn_cer.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txt_vtn_btn_cer.setForeground(new java.awt.Color(255, 255, 255));
        txt_vtn_btn_cer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_vtn_btn_cer.setText("x");
        txt_vtn_btn_cer.setToolTipText("Cerrar");
        txt_vtn_btn_cer.setBorder(null);
        txt_vtn_btn_cer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_vtn_btn_cer.setOpaque(true);
        txt_vtn_btn_cer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_vtn_btn_cerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_vtn_btn_cerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_vtn_btn_cerMouseExited(evt);
            }
        });

        txt_vtn_ico.setBackground(new java.awt.Color(211, 111, 66));
        txt_vtn_ico.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        txt_vtn_ico.setBorder(null);
        txt_vtn_ico.setContentAreaFilled(false);
        txt_vtn_ico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_vtn_ico.setFocusPainted(false);
        txt_vtn_ico.setPreferredSize(new java.awt.Dimension(55, 26));

        javax.swing.GroupLayout pnl_principal_cabeceraLayout = new javax.swing.GroupLayout(pnl_principal_cabecera);
        pnl_principal_cabecera.setLayout(pnl_principal_cabeceraLayout);
        pnl_principal_cabeceraLayout.setHorizontalGroup(
            pnl_principal_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_principal_cabeceraLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txt_vtn_ico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txt_vtn_tit, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(txt_vtn_btn_cer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_principal_cabeceraLayout.setVerticalGroup(
            pnl_principal_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_vtn_ico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_principal_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_vtn_tit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txt_vtn_btn_cer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        lbl_msj_ico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_msj_ico.setBorder(null);
        lbl_msj_ico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txt_vtn_tit1.setFont(new java.awt.Font("Segoe UI Light", 1, 9)); // NOI18N
        txt_vtn_tit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_vtn_tit1.setText("DETALLES DEL CERTIFICADO");
        txt_vtn_tit1.setBorder(null);

        txt_vtn_tit2.setFont(new java.awt.Font("Segoe UI Light", 1, 9)); // NOI18N
        txt_vtn_tit2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_vtn_tit2.setText("INFORMACIÓN DEL CERTIFICADO");
        txt_vtn_tit2.setBorder(null);

        txt_vtn_tit3.setFont(new java.awt.Font("Segoe UI Light", 1, 9)); // NOI18N
        txt_vtn_tit3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_vtn_tit3.setText("EL CERTIFICADO PUEDE SER UTILIZADO BAJO ÉSTAS CONDICIONES :");
        txt_vtn_tit3.setBorder(null);

        lbl_crt_usos.setFont(new java.awt.Font("Segoe UI Light", 1, 9)); // NOI18N
        lbl_crt_usos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_crt_usos.setText("NO REPUDATION");
        lbl_crt_usos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel3.setBackground(new java.awt.Color(241, 241, 241));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel1.setText("EMITIDO PARA");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel2.setText("CARGO");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel3.setText("EMPRESA");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel4.setText("VÁLIDO DESDE");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel5.setText("UNIDAD ORGANIZACIONAL");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel6.setText("USOS");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel7.setText("EMITIDO POR");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel8.setText("ALIAS");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel9.setText("VÁLIDO HASTA");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel10.setText("NUMERO DE SERIE");

        lbl_crt_emi_por.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbl_crt_emi_por.setText("EMITIDO POR");

        lbl_crt_emi_par.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbl_crt_emi_par.setText("EMITIDO POR");

        lbl_crt_alia.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbl_crt_alia.setText("EMITIDO POR");

        lbl_crt_crg.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbl_crt_crg.setText("EMITIDO POR");

        lbl_crt_emp.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbl_crt_emp.setText("EMITIDO POR");

        lbl_crt_ser_num.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbl_crt_ser_num.setText("EMITIDO POR");

        lbl_crt_uni_org.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbl_crt_uni_org.setText("EMITIDO POR");

        lbl_crt_val_des.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbl_crt_val_des.setText("EMITIDO POR");

        lbl_crt_val_has.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbl_crt_val_has.setText("EMITIDO POR");

        lbl_crt_uso.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbl_crt_uso.setText("EMITIDO POR");

        lbl_crt_emi_ver.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        lbl_crt_emi_ver.setForeground(new java.awt.Color(0, 51, 102));
        lbl_crt_emi_ver.setText("ver");
        lbl_crt_emi_ver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_crt_emi_ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_crt_emi_verMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_crt_emi_por, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lbl_crt_emi_ver))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_crt_emi_par, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_crt_alia, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_crt_crg, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_crt_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_crt_ser_num, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(lbl_crt_uni_org, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_crt_val_des, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_crt_val_has, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_crt_uso, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_crt_emi_por)
                    .addComponent(lbl_crt_emi_ver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_crt_emi_par))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_crt_alia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_crt_crg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_crt_emp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbl_crt_ser_num, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_crt_uni_org))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_crt_val_des))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_crt_val_has))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_crt_uso))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_msj_ico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_vtn_tit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_vtn_tit1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_vtn_tit3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_crt_usos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_vtn_tit2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_msj_ico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_vtn_tit3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_crt_usos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_vtn_tit1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCertificadoDetalles.setViewportView(jPanel1);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCertificadoDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_principal_cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(pnlCertificadoDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPrincipalLayout.createSequentialGroup()
                    .addComponent(pnl_principal_cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 468, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_vtn_btn_cerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_vtn_btn_cerMouseClicked
//        vg_valor_enviar=CERRAR;
        frmMensaje.ventana_cerrar(this);
    }//GEN-LAST:event_txt_vtn_btn_cerMouseClicked

    private void txt_vtn_btn_cerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_vtn_btn_cerMouseEntered
        // cambiarColor((javax.swing.JLabel)evt.getSource(),Color.red,Color.white);
    }//GEN-LAST:event_txt_vtn_btn_cerMouseEntered

    private void txt_vtn_btn_cerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_vtn_btn_cerMouseExited
        // cambiarColor((javax.swing.JLabel)evt.getSource(),new Color(255,153,153),Color.white);
    }//GEN-LAST:event_txt_vtn_btn_cerMouseExited

    private void lbl_crt_emi_verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_crt_emi_verMouseClicked
//        Repositorio rep= frmFirmador.repositorios;
//        rep.validarAlias(lbl_crt_emi_por.getText());
//        X509Certificate x509Certificate=rep.getCertificadox509();
//        rep.validarAlias(null)
//        new frmCertificadoPropiedades(this, true,).setVisible(true);
    }//GEN-LAST:event_lbl_crt_emi_verMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_crt_alia;
    private javax.swing.JLabel lbl_crt_crg;
    private javax.swing.JLabel lbl_crt_emi_par;
    private javax.swing.JLabel lbl_crt_emi_por;
    private javax.swing.JLabel lbl_crt_emi_ver;
    private javax.swing.JLabel lbl_crt_emp;
    private javax.swing.JLabel lbl_crt_ser_num;
    private javax.swing.JLabel lbl_crt_uni_org;
    private javax.swing.JLabel lbl_crt_uso;
    private static javax.swing.JLabel lbl_crt_usos;
    private javax.swing.JLabel lbl_crt_val_des;
    private javax.swing.JLabel lbl_crt_val_has;
    private static javax.swing.JLabel lbl_msj_ico;
    private javax.swing.JScrollPane pnlCertificadoDetalles;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnl_principal_cabecera;
    private javax.swing.JLabel txt_vtn_btn_cer;
    private static javax.swing.JButton txt_vtn_ico;
    private static javax.swing.JLabel txt_vtn_tit;
    private static javax.swing.JLabel txt_vtn_tit1;
    private static javax.swing.JLabel txt_vtn_tit2;
    private static javax.swing.JLabel txt_vtn_tit3;
    // End of variables declaration//GEN-END:variables
}
