/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import static Formularios.frmConfigurador.configuracion;
import java.awt.Color;
import javax.swing.JButton;

public class frmDatosExtras extends javax.swing.JDialog {
    
    public frmDatosExtras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ctrl_txt_firma_visible_motivo.requestFocus();
        ctrl_txt_firma_visible_motivo.setText(configuracion.getVg_motivo());
        //ctrl_txt_firma_visible_motivo.setText("SSigner Configuración v 2.5.1.1");
        if(ctrl_txt_firma_visible_motivo.getText().length()>0){
            ctrl_txt_firma_visible_motivo.setSelectionStart(0);
            ctrl_txt_firma_visible_motivo.setSelectionEnd(ctrl_txt_firma_visible_motivo.getText().length());
        }

        //ctrl_txt_firma_visible_localidad.setText(configuracion.getVg_localidad());
        ctrl_txt_firma_visible_localidad.setText("SSigner Configuración v 2.5.1.1");

        if (ctrl_txt_firma_visible_localidad.getText().length() > 0) {
            ctrl_txt_firma_visible_localidad.setEnabled(false);  // Deshabilitar el campo
            ctrl_txt_firma_visible_localidad.setBackground(new Color(105, 105, 105));  // Cambiar el fondo a gris
            ctrl_txt_firma_visible_localidad.setForeground(new Color(25, 25, 112) );
        } else {
            ctrl_txt_firma_visible_localidad.setEnabled(true);  // Habilitar el campo si no está seteado
            ctrl_txt_firma_visible_localidad.setBackground(Color.WHITE);  // Fondo blanco
        }
        
        ctrl_txt_auxiliar.setVisible(false);
        ctrl_chk_ventana_volver_mostrar.setSelected(frmConfigurador.configuracion.isVg_ventana_volver_abrir());
        setLocationRelativeTo(parent);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pnlOtrosDatos = new javax.swing.JPanel();
        pnlBarra5 = new javax.swing.JPanel();
        lblCerrar5 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnCargar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ctrl_btn_continuar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ctrl_txt_firma_visible_motivo = new javax.swing.JTextField();
        ctrl_txt_firma_visible_localidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ctrl_chk_ventana_volver_mostrar = new javax.swing.JCheckBox();
        ctrl_txt_auxiliar = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        pnlOtrosDatos.setBackground(new java.awt.Color(241, 241, 241));
        pnlOtrosDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlBarra5.setBackground(new java.awt.Color(241, 241, 241));

        lblCerrar5.setBackground(new java.awt.Color(255, 153, 153));
        lblCerrar5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblCerrar5.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar5.setText("x");
        lblCerrar5.setToolTipText("Cerrar");
        lblCerrar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar5.setOpaque(true);
        lblCerrar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrar5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrar5MouseExited(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Motivo y Version");

        btnCargar2.setBackground(new java.awt.Color(211, 111, 66));
        btnCargar2.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        btnCargar2.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar2.setToolTipText("Cargar documentos para visualzar.");
        btnCargar2.setAutoscrolls(true);
        btnCargar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnCargar2.setBorderPainted(false);
        btnCargar2.setContentAreaFilled(false);
        btnCargar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargar2.setFocusPainted(false);
        btnCargar2.setPreferredSize(new java.awt.Dimension(55, 26));
        btnCargar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCargar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCargar2MouseExited(evt);
            }
        });
        btnCargar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBarra5Layout = new javax.swing.GroupLayout(pnlBarra5);
        pnlBarra5.setLayout(pnlBarra5Layout);
        pnlBarra5Layout.setHorizontalGroup(
            pnlBarra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarra5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCargar2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCerrar5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlBarra5Layout.setVerticalGroup(
            pnlBarra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarra5Layout.createSequentialGroup()
                .addGroup(pnlBarra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCerrar5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBarra5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnlBarra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCargar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ctrl_btn_continuar.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        ctrl_btn_continuar.setText("Aceptar");
        ctrl_btn_continuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ctrl_btn_continuar.setFocusPainted(false);
        ctrl_btn_continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ctrl_btn_continuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ctrl_btn_continuarMouseExited(evt);
            }
        });
        ctrl_btn_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrl_btn_continuarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(241, 241, 241));

        ctrl_txt_firma_visible_motivo.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        ctrl_txt_firma_visible_motivo.setForeground(new java.awt.Color(211, 111, 66));
        ctrl_txt_firma_visible_motivo.setPreferredSize(new java.awt.Dimension(332, 27));
        ctrl_txt_firma_visible_motivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ctrl_txt_firma_visible_motivoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ctrl_txt_firma_visible_motivoFocusLost(evt);
            }
        });

        ctrl_txt_firma_visible_localidad.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        ctrl_txt_firma_visible_localidad.setForeground(new java.awt.Color(211, 111, 66));
        ctrl_txt_firma_visible_localidad.setPreferredSize(new java.awt.Dimension(332, 27));
        ctrl_txt_firma_visible_localidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ctrl_txt_firma_visible_localidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ctrl_txt_firma_visible_localidadFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 83, 154));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Motivo : ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 83, 154));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Version : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctrl_txt_firma_visible_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctrl_txt_firma_visible_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctrl_txt_firma_visible_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctrl_txt_firma_visible_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ctrl_chk_ventana_volver_mostrar.setBackground(new java.awt.Color(255, 255, 255));
        ctrl_chk_ventana_volver_mostrar.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ctrl_chk_ventana_volver_mostrar.setForeground(new java.awt.Color(0, 83, 154));
        ctrl_chk_ventana_volver_mostrar.setText("No volver a mostrar este cuadro de diálogo");
        ctrl_chk_ventana_volver_mostrar.setContentAreaFilled(false);
        ctrl_chk_ventana_volver_mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ctrl_chk_ventana_volver_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrl_chk_ventana_volver_mostrarActionPerformed(evt);
            }
        });

        ctrl_txt_auxiliar.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        ctrl_txt_auxiliar.setForeground(new java.awt.Color(211, 111, 66));
        ctrl_txt_auxiliar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ctrl_txt_auxiliarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ctrl_txt_auxiliarFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ctrl_chk_ventana_volver_mostrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(ctrl_btn_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(92, 92, 92)
                            .addComponent(ctrl_txt_auxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctrl_btn_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctrl_txt_auxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrl_chk_ventana_volver_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlOtrosDatosLayout = new javax.swing.GroupLayout(pnlOtrosDatos);
        pnlOtrosDatos.setLayout(pnlOtrosDatosLayout);
        pnlOtrosDatosLayout.setHorizontalGroup(
            pnlOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOtrosDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlBarra5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlOtrosDatosLayout.setVerticalGroup(
            pnlOtrosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOtrosDatosLayout.createSequentialGroup()
                .addComponent(pnlBarra5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOtrosDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlOtrosDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void cerrarVentana(){
        setVisible(false);
        dispose();
    }
    protected void cambiarColor(Object obj,Color colorfondo,Color colorletra){
        if(obj instanceof javax.swing.JLabel){
            ((javax.swing.JLabel) obj).setBackground(colorfondo);
            ((javax.swing.JLabel) obj).setForeground(colorletra);
            ((javax.swing.JLabel) obj).setOpaque(true);
        }
        else if(obj instanceof JButton){
            ((javax.swing.JButton) obj).setBackground(colorfondo);
            ((javax.swing.JButton) obj).setForeground(colorletra);
            ((javax.swing.JButton) obj).setOpaque(true);
            ((javax.swing.JButton) obj).setBorder(javax.swing.BorderFactory.createLineBorder(colorletra));
        } 
    }
    void focodentro(javax.swing.JTextField cajatexto){
        cajatexto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(67,73,111), 2, true));
    }
    void focofuera(javax.swing.JTextField cajatexto){
        cajatexto.setBorder(ctrl_txt_auxiliar.getBorder());
    }  
    private void lblCerrar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar5MouseClicked
        cerrarVentana();
    }//GEN-LAST:event_lblCerrar5MouseClicked

    private void lblCerrar5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar5MouseEntered
        cambiarColor((javax.swing.JLabel)evt.getSource(),java.awt.Color.red,java.awt.Color.white);
    }//GEN-LAST:event_lblCerrar5MouseEntered

    private void lblCerrar5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar5MouseExited
        cambiarColor((javax.swing.JLabel)evt.getSource(),new java.awt.Color(255,153,153),java.awt.Color.WHITE);
    }//GEN-LAST:event_lblCerrar5MouseExited

    private void ctrl_btn_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrl_btn_continuarActionPerformed
        configuracion.setVg_motivo(ctrl_txt_firma_visible_motivo.getText());
        configuracion.setVg_localidad(ctrl_txt_firma_visible_localidad.getText());
        configuracion.setVg_ventana_volver_abrir(ctrl_chk_ventana_volver_mostrar.isSelected());
        setVisible(false);
        dispose();
    }//GEN-LAST:event_ctrl_btn_continuarActionPerformed

    
    private void ctrl_btn_continuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctrl_btn_continuarMouseEntered
       
    }//GEN-LAST:event_ctrl_btn_continuarMouseEntered

    private void ctrl_btn_continuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctrl_btn_continuarMouseExited
        
    }//GEN-LAST:event_ctrl_btn_continuarMouseExited

    private void ctrl_txt_firma_visible_motivoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctrl_txt_firma_visible_motivoFocusGained
        focodentro((javax.swing.JTextField)evt.getSource());
    }//GEN-LAST:event_ctrl_txt_firma_visible_motivoFocusGained

    private void ctrl_txt_firma_visible_motivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctrl_txt_firma_visible_motivoFocusLost
         focofuera((javax.swing.JTextField)evt.getSource());
    }//GEN-LAST:event_ctrl_txt_firma_visible_motivoFocusLost

    private void ctrl_txt_firma_visible_localidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctrl_txt_firma_visible_localidadFocusGained
         focodentro((javax.swing.JTextField)evt.getSource());
    }//GEN-LAST:event_ctrl_txt_firma_visible_localidadFocusGained

    private void ctrl_txt_firma_visible_localidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctrl_txt_firma_visible_localidadFocusLost
        focofuera((javax.swing.JTextField)evt.getSource());
    }//GEN-LAST:event_ctrl_txt_firma_visible_localidadFocusLost

    private void btnCargar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar2MouseEntered

    private void btnCargar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar2MouseExited

    private void btnCargar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar2ActionPerformed

    private void ctrl_chk_ventana_volver_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrl_chk_ventana_volver_mostrarActionPerformed
        frmConfigurador.configuracion.setVg_ventana_volver_abrir(ctrl_chk_ventana_volver_mostrar.isSelected());
    }//GEN-LAST:event_ctrl_chk_ventana_volver_mostrarActionPerformed

    private void ctrl_txt_auxiliarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctrl_txt_auxiliarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ctrl_txt_auxiliarFocusGained

    private void ctrl_txt_auxiliarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctrl_txt_auxiliarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ctrl_txt_auxiliarFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCargar2;
    public javax.swing.JButton ctrl_btn_continuar;
    protected static javax.swing.JCheckBox ctrl_chk_ventana_volver_mostrar;
    private javax.swing.JTextField ctrl_txt_auxiliar;
    private javax.swing.JTextField ctrl_txt_firma_visible_localidad;
    private javax.swing.JTextField ctrl_txt_firma_visible_motivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCerrar5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBarra5;
    private javax.swing.JPanel pnlOtrosDatos;
    // End of variables declaration//GEN-END:variables
}
