/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author usuario
 */
public class frmSoporte extends javax.swing.JDialog {

    /**
     * Creates new form frmSoporte
     */
    public frmSoporte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btn_logo.setIcon(frmConfigurador.btnLogo.getIcon());
        setLocationRelativeTo(parent);
    }
    private void cerrarVentana(){
            setVisible(false);
            dispose();
    }
    protected void cambiarColor(Object obj){
        cambiarColor(obj,Color.lightGray,Color.white);
    }
    protected void cambiarColor(Object obj,Color colorfondo,Color colorletra){
        if(obj instanceof javax.swing.JLabel){
            ((javax.swing.JLabel) obj).setBackground(colorfondo);
            ((javax.swing.JLabel) obj).setForeground(colorletra);
            ((javax.swing.JLabel) obj).setOpaque(true);
        }
        else if(obj instanceof JButton){
            ((JButton) obj).setBackground(colorfondo);
            ((javax.swing.JLabel) obj).setForeground(colorletra);
            ((javax.swing.JLabel) obj).setOpaque(true);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnCargar1 = new javax.swing.JButton();
        pnlBarra3 = new javax.swing.JPanel();
        lblCerrar3 = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        btn_logo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ctrl_lbl_ir_url_salmon1 = new javax.swing.JLabel();
        ctrl_lbl_ver_manual2 = new javax.swing.JLabel();
        ctrl_lbl_ver_manual1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ctrl_txt_cuerpo_descripcion = new javax.swing.JTextPane();
        ctrl_lbl_ver_manual4 = new javax.swing.JLabel();
        ctrl_lbl_ir_url_salmon2 = new javax.swing.JLabel();
        ctrl_lbl_ver_manual3 = new javax.swing.JLabel();
        ctrl_lbl_ir_url_salmon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCargar1.setBackground(new java.awt.Color(211, 111, 66));
        btnCargar1.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        btnCargar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar1.setToolTipText("Cargar documentos para visualzar.");
        btnCargar1.setAutoscrolls(true);
        btnCargar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnCargar1.setBorderPainted(false);
        btnCargar1.setContentAreaFilled(false);
        btnCargar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargar1.setFocusPainted(false);
        btnCargar1.setPreferredSize(new java.awt.Dimension(55, 26));
        btnCargar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCargar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCargar1MouseExited(evt);
            }
        });
        btnCargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargar1ActionPerformed(evt);
            }
        });

        pnlBarra3.setBackground(new java.awt.Color(241, 241, 241));
        pnlBarra3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        pnlBarra3.setOpaque(false);

        lblCerrar3.setBackground(new java.awt.Color(255, 153, 153));
        lblCerrar3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblCerrar3.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar3.setText("x");
        lblCerrar3.setToolTipText("Cerrar");
        lblCerrar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar3.setOpaque(true);
        lblCerrar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrar3MouseExited(evt);
            }
        });

        lbltitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("Soporte");

        javax.swing.GroupLayout pnlBarra3Layout = new javax.swing.GroupLayout(pnlBarra3);
        pnlBarra3.setLayout(pnlBarra3Layout);
        pnlBarra3Layout.setHorizontalGroup(
            pnlBarra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarra3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(lblCerrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBarra3Layout.setVerticalGroup(
            pnlBarra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblCerrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_logo.setContentAreaFilled(false);

        ctrl_lbl_ir_url_salmon1.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ctrl_lbl_ir_url_salmon1.setForeground(new java.awt.Color(0, 51, 204));
        ctrl_lbl_ir_url_salmon1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ctrl_lbl_ir_url_salmon1.setText("info@saeta.pe");
        ctrl_lbl_ir_url_salmon1.setToolTipText("www.salmoncorp.com/salmonsigner");
        ctrl_lbl_ir_url_salmon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ctrl_lbl_ver_manual2.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ctrl_lbl_ver_manual2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ctrl_lbl_ver_manual2.setText("Av. General Vidal #921. Breña. Lima - Perú");
        ctrl_lbl_ver_manual2.setToolTipText("clic para ver manual de usuario");
        ctrl_lbl_ver_manual2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ctrl_lbl_ver_manual1.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ctrl_lbl_ver_manual1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ctrl_lbl_ver_manual1.setText("Salmón Corp S.A.C");
        ctrl_lbl_ver_manual1.setToolTipText("clic para ver manual de usuario");
        ctrl_lbl_ver_manual1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jScrollPane1.setBorder(null);

        ctrl_txt_cuerpo_descripcion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        ctrl_txt_cuerpo_descripcion.setText("De no comprender en su totalidad sobre los proceso de SSigner Configurador o tiene alguna duda, contáctenos al siguiente correo:");
        ctrl_txt_cuerpo_descripcion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ctrl_txt_cuerpo_descripcion.setEnabled(false);
        jScrollPane1.setViewportView(ctrl_txt_cuerpo_descripcion);

        ctrl_lbl_ver_manual4.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ctrl_lbl_ver_manual4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ctrl_lbl_ver_manual4.setText("T.+(51-1) 332 3576");
        ctrl_lbl_ver_manual4.setToolTipText("clic para ver manual de usuario");
        ctrl_lbl_ver_manual4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ctrl_lbl_ir_url_salmon2.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ctrl_lbl_ir_url_salmon2.setForeground(new java.awt.Color(0, 51, 204));
        ctrl_lbl_ir_url_salmon2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ctrl_lbl_ir_url_salmon2.setText("www.saeta.pe/ssigner");
        ctrl_lbl_ir_url_salmon2.setToolTipText("www.salmoncorp.com/salmonsigner");
        ctrl_lbl_ir_url_salmon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ctrl_lbl_ver_manual3.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ctrl_lbl_ver_manual3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ctrl_lbl_ver_manual3.setText("T.+(51-1) 332 0797 / 333 2200");
        ctrl_lbl_ver_manual3.setToolTipText("clic para ver manual de usuario");
        ctrl_lbl_ver_manual3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ctrl_lbl_ir_url_salmon.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        ctrl_lbl_ir_url_salmon.setForeground(new java.awt.Color(0, 51, 204));
        ctrl_lbl_ir_url_salmon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ctrl_lbl_ir_url_salmon.setText("soporte@saeta.pe");
        ctrl_lbl_ir_url_salmon.setToolTipText("www.salmoncorp.com/salmonsigner");
        ctrl_lbl_ir_url_salmon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctrl_lbl_ir_url_salmon2)
                            .addComponent(ctrl_lbl_ir_url_salmon1)
                            .addComponent(ctrl_lbl_ir_url_salmon)
                            .addComponent(ctrl_lbl_ver_manual2)
                            .addComponent(ctrl_lbl_ver_manual1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ctrl_lbl_ver_manual3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ctrl_lbl_ver_manual4)))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrl_lbl_ir_url_salmon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrl_lbl_ver_manual1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrl_lbl_ver_manual2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrl_lbl_ir_url_salmon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctrl_lbl_ver_manual3)
                    .addComponent(ctrl_lbl_ver_manual4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrl_lbl_ir_url_salmon2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBarra3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBarra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar1MouseEntered

    private void btnCargar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar1MouseExited

    private void btnCargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar1ActionPerformed

    private void lblCerrar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar3MouseClicked
        cerrarVentana();
    }//GEN-LAST:event_lblCerrar3MouseClicked

    private void lblCerrar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar3MouseEntered
        cambiarColor((javax.swing.JLabel)evt.getSource(),Color.red,Color.white);
    }//GEN-LAST:event_lblCerrar3MouseEntered

    private void lblCerrar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar3MouseExited
        cambiarColor((javax.swing.JLabel)evt.getSource(),new Color(255,153,153),Color.white);
    }//GEN-LAST:event_lblCerrar3MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCargar1;
    private javax.swing.JButton btn_logo;
    private javax.swing.JLabel ctrl_lbl_ir_url_salmon;
    private javax.swing.JLabel ctrl_lbl_ir_url_salmon1;
    private javax.swing.JLabel ctrl_lbl_ir_url_salmon2;
    private javax.swing.JLabel ctrl_lbl_ver_manual1;
    private javax.swing.JLabel ctrl_lbl_ver_manual2;
    private javax.swing.JLabel ctrl_lbl_ver_manual3;
    private javax.swing.JLabel ctrl_lbl_ver_manual4;
    private javax.swing.JTextPane ctrl_txt_cuerpo_descripcion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCerrar3;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel pnlBarra3;
    // End of variables declaration//GEN-END:variables
}
